name:          Code Guide by @spiraldev
description:   Standards for developing flexible, durable, and sustainable HTML and CSS. And ColdFusion Cheat sheet.
url:           http://spiraldev.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
